-- Migration: add_pre_orders.sql
-- Purpose: Phase 11 / 11.1 — Pre-orders & waitlist.
--
-- Adds:
--   1. pre_orders         — one row per pre-order (walk-in or catalog)
--   2. pre_order_events   — full audit trail of what happened to it
--   3. products.shipping_per_kg  — sea-cargo rate per kg for this style
--   4. products.pre_order_enabled — gate which products are pre-orderable
--   5. product_variants.cost_price — per-size cost override (optional)
--
-- Design:
--   - Pricing snapshot (unit_cost, shipping_cost, unit_price, deposit_amount,
--     balance_due) is captured at pre-order time, not derived. This means
--     we can re-issue a receipt months later and the numbers still match.
--   - tracking_code is a short, public-friendly code (e.g. PR-2026-0042).
--     Generated by the action layer, not here — we just store and index it.
--   - source ('pos' | 'catalog') lets us report on which funnel is working.
--   - shipping_mode ('sea' | 'air') controls expected delivery date and
--     shipping cost formula. Sea = +50 days, air = +14 days.
--   - All status transitions are timestamped individually so the event
--     timeline shows what happened when. The pre_order_events table holds
--     the full story; status fields on the row are just denormalised
--     for fast filtering.
--
-- Re-runnable: every statement is idempotent.

-- ─────────────────────────────────────────────────────────────────────
-- 1. pre_orders
-- ─────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS pre_orders (
  id                    UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  -- Public tracking code, e.g. "PR-2026-0042". Generated by the action
  -- layer; we just enforce uniqueness here.
  tracking_code         TEXT UNIQUE,

  -- Customer (can be a walk-in — no client_id required)
  customer_id           UUID REFERENCES clients(id) ON DELETE SET NULL,
  customer_name         TEXT NOT NULL,
  customer_whatsapp     TEXT NOT NULL,

  -- Product + variant
  product_id            UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  variant_id            UUID REFERENCES product_variants(id) ON DELETE SET NULL,

  -- Pricing snapshot (captured at order time, not derived)
  unit_cost             NUMERIC(14, 2) NOT NULL CHECK (unit_cost >= 0),
  shipping_cost         NUMERIC(14, 2) NOT NULL CHECK (shipping_cost >= 0),
  unit_price            NUMERIC(14, 2) NOT NULL CHECK (unit_price > 0),
  deposit_amount        NUMERIC(14, 2) NOT NULL CHECK (deposit_amount > 0),
  balance_due           NUMERIC(14, 2) NOT NULL CHECK (balance_due >= 0),

  -- Shipping
  shipping_mode         TEXT NOT NULL CHECK (shipping_mode IN ('sea', 'air')),

  -- Funnel: 'pos' (walk-in) or 'catalog' (online)
  source                TEXT NOT NULL CHECK (source IN ('pos', 'catalog')),

  -- Status (transitions are validated by the action layer; CHECK
  -- just protects against bad writes)
  status                TEXT NOT NULL DEFAULT 'pending'
                          CHECK (status IN (
                            'pending', 'deposit_paid', 'arrived',
                            'completed', 'cancelled', 'refunded'
                          )),

  -- Delivery target (computed from shipping_mode at order time)
  expected_delivery_date DATE NOT NULL,

  -- Optional customer-facing notes
  notes                 TEXT,

  -- Denormalised status timestamps (the events table holds the
  -- full timeline; these are for fast filtering and reporting)
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deposit_paid_at       TIMESTAMPTZ,
  arrived_at            TIMESTAMPTZ,
  completed_at          TIMESTAMPTZ,
  cancelled_at          TIMESTAMPTZ,
  refunded_at           TIMESTAMPTZ,

  -- Set when the pre-order converts to a sale
  sale_id               UUID REFERENCES sales(id) ON DELETE SET NULL
);

-- Indexes
-- 1) Default admin list: by status + created_at desc
CREATE INDEX IF NOT EXISTS idx_pre_orders_status_created
  ON pre_orders (status, created_at DESC);

-- 2) Customer lookup by WhatsApp (catalog self-serve + tracking)
CREATE INDEX IF NOT EXISTS idx_pre_orders_whatsapp
  ON pre_orders (customer_whatsapp);

-- 3) Tracking code (already UNIQUE but explicit index for clarity)
CREATE INDEX IF NOT EXISTS idx_pre_orders_tracking_code
  ON pre_orders (tracking_code);

-- 4) Active pre-orders for a product (used by the catalog to show
-- "N people waiting" hint on the product page)
CREATE INDEX IF NOT EXISTS idx_pre_orders_product_active
  ON pre_orders (product_id, status)
  WHERE status IN ('pending', 'deposit_paid', 'arrived');

-- updated_at trigger
CREATE OR REPLACE FUNCTION pre_orders_touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_pre_orders_touch_updated_at ON pre_orders;
CREATE TRIGGER trg_pre_orders_touch_updated_at
  BEFORE UPDATE ON pre_orders
  FOR EACH ROW
  EXECUTE FUNCTION pre_orders_touch_updated_at();

-- RLS
ALTER TABLE pre_orders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can manage pre_orders"
  ON pre_orders;
CREATE POLICY "Authenticated users can manage pre_orders"
  ON pre_orders
  FOR ALL
  TO authenticated
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- ─────────────────────────────────────────────────────────────────────
-- 2. pre_order_events
-- ─────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS pre_order_events (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  pre_order_id    UUID NOT NULL REFERENCES pre_orders(id) ON DELETE CASCADE,
  -- 'created' | 'deposit_paid' | 'notified' | 'arrived' |
  -- 'balance_paid' | 'completed' | 'cancelled' | 'refunded' |
  -- 'status_changed' | 'message_queued' | 'message_sent'
  event_type      TEXT NOT NULL,
  -- Free-form JSON. Always at least { from, to } on status_changed;
  -- { amount, method } on payment events.
  event_data      JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pre_order_events_order
  ON pre_order_events (pre_order_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_pre_order_events_type
  ON pre_order_events (event_type, created_at DESC);

-- RLS
ALTER TABLE pre_order_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can manage pre_order_events"
  ON pre_order_events;
CREATE POLICY "Authenticated users can manage pre_order_events"
  ON pre_order_events
  FOR ALL
  TO authenticated
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- ─────────────────────────────────────────────────────────────────────
-- 3. products.shipping_per_kg + pre_order_enabled
-- ─────────────────────────────────────────────────────────────────────

ALTER TABLE products
  ADD COLUMN IF NOT EXISTS shipping_per_kg   NUMERIC(10, 2) CHECK (shipping_per_kg >= 0),
  ADD COLUMN IF NOT EXISTS pre_order_enabled BOOLEAN NOT NULL DEFAULT FALSE;

COMMENT ON COLUMN products.shipping_per_kg IS
  'Sea-cargo shipping cost per kg for this product. Used by the pre-order deposit calculation.';

COMMENT ON COLUMN products.pre_order_enabled IS
  'Whether this product is open for pre-orders (catalog and POS). Phase 11.';

-- ─────────────────────────────────────────────────────────────────────
-- 4. product_variants.cost_price (per-size override)
-- ─────────────────────────────────────────────────────────────────────

ALTER TABLE product_variants
  ADD COLUMN IF NOT EXISTS cost_price NUMERIC(14, 2) CHECK (cost_price >= 0);

COMMENT ON COLUMN product_variants.cost_price IS
  'Optional per-size cost override. If null, fall back to products.cost_price. Phase 11.';

-- ─────────────────────────────────────────────────────────────────────
-- Comments
-- ─────────────────────────────────────────────────────────────────────

COMMENT ON TABLE pre_orders IS
  'Pre-orders and waitlist registrations. Both walk-in (POS) and online (catalog) flow into the same row. Status transitions are timestamped on the row; full event timeline in pre_order_events. Phase 11.';

COMMENT ON COLUMN pre_orders.tracking_code IS
  'Short public code shown to the customer, e.g. PR-2026-0042. Lets them look up their pre-order on the catalog without an account.';

COMMENT ON COLUMN pre_orders.source IS
  'pos = walk-in, registered at the counter. catalog = online, via the public catalog form.';

COMMENT ON TABLE pre_order_events IS
  'Audit trail for pre_orders. One row per state change or notification. Phase 11.';
