-- Migration: add_forecasts_table.sql
-- Purpose: Phase 7 / 7.1 from ROADMAP.md — create the `forecasts` table
--          that backs every predictive surface in the app:
--          - product demand forecasting (7.2)
--          - cash-flow forecasting (7.3)
--          - client default-risk scoring (7.4)
--          - smart reorder alerts (7.7)
--          - dashboard forecast widget (7.5)
--
-- Design notes:
--   * `kind` discriminates the forecast type. The combination of
--     (kind, target_id, horizon_days) is the natural lookup key.
--   * `target_id` is nullable because business-wide forecasts
--     (cashflow) don't have a specific target row. For demand
--     forecasts it points to products.id; for default_risk it
--     points to clients.id. We don't enforce an FK because the
--     referenced table depends on `kind` — that's a chicken-and-egg
--     problem in Postgres, so the application layer enforces it.
--   * `payload` is jsonb. The shape depends on `kind` (see
--     lib/actions/forecast.ts for the TypeScript types).
--   * `generated_at` + `expires_at` let the nightly Vercel Cron
--     (7.8) find rows that need regeneration. The cron does
--     `SELECT ... WHERE expires_at < now()`.
--   * `model` records which algorithm produced the row
--     ('simple-moving-avg', 'groq-llama-3.3-70b', 'rule-based',
--     etc.) so we can later analyze which models are most
--     accurate and A/B them.
--
-- Re-runnable: every statement uses IF NOT EXISTS / OR REPLACE
-- patterns so this migration can be applied multiple times.

-- ─────────────────────────────────────────────────────────────────────
-- Table
-- ─────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS forecasts (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  -- 'demand' | 'cashflow' | 'default_risk'
  kind            TEXT NOT NULL CHECK (kind IN ('demand', 'cashflow', 'default_risk')),
  -- NULL for business-wide forecasts (cashflow). For 'demand' this
  -- is products.id; for 'default_risk' this is clients.id. No FK
  -- because the referenced table depends on `kind`.
  target_id       UUID,
  -- How far the forecast extends, in days. 7, 30, 60, 90 are
  -- typical values. Required for all kinds.
  horizon_days    INTEGER NOT NULL CHECK (horizon_days > 0 AND horizon_days <= 365),
  -- The forecast itself. Shape varies by kind; see lib/actions/forecast.ts.
  payload         JSONB NOT NULL,
  -- The model that produced this forecast. Free-form text for now;
  -- we may add a CHECK constraint later once the set of models
  -- stabilises.
  model           TEXT NOT NULL,
  generated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- When the forecast goes stale and should be regenerated by the
  -- nightly cron (7.8). Defaults to generated_at + 1 day.
  expires_at      TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '1 day'),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────
-- Indexes
--
-- The (kind, target_id, horizon_days) triple is the natural lookup
-- key for "give me the current demand forecast for product X over
-- 30 days". A separate (kind, expires_at) index backs the cron
-- query that finds expired rows to regenerate.
-- ─────────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_forecasts_lookup
  ON forecasts (kind, target_id, horizon_days);

CREATE INDEX IF NOT EXISTS idx_forecasts_expires
  ON forecasts (kind, expires_at)
  WHERE expires_at IS NOT NULL;

-- ─────────────────────────────────────────────────────────────────────
-- updated_at trigger
--
-- Touch updated_at on every UPDATE so the app can show "last
-- regenerated" reliably. Mirrors the pattern on the existing
-- products / clients tables.
-- ─────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION forecasts_touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_forecasts_touch_updated_at ON forecasts;
CREATE TRIGGER trg_forecasts_touch_updated_at
  BEFORE UPDATE ON forecasts
  FOR EACH ROW
  EXECUTE FUNCTION forecasts_touch_updated_at();

-- ─────────────────────────────────────────────────────────────────────
-- RLS
-- ─────────────────────────────────────────────────────────────────────

ALTER TABLE forecasts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can manage forecasts" ON forecasts;
CREATE POLICY "Authenticated users can manage forecasts"
  ON forecasts
  FOR ALL
  TO authenticated
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- ─────────────────────────────────────────────────────────────────────
-- Helpful comments
-- ─────────────────────────────────────────────────────────────────────

COMMENT ON TABLE forecasts IS
  'Predictive AI / forecasting cache. One row per (kind, target_id, horizon_days). The nightly Vercel Cron (Phase 7.8) regenerates expired rows.';

COMMENT ON COLUMN forecasts.kind IS
  'demand = per-product sales forecast; cashflow = business-wide inflows/outflows; default_risk = per-client probability of missing a payment.';

COMMENT ON COLUMN forecasts.target_id IS
  'NULL for business-wide forecasts. For demand: products.id. For default_risk: clients.id.';

COMMENT ON COLUMN forecasts.payload IS
  'Forecast data. Shape depends on kind. See lib/actions/forecast.ts for the TypeScript types.';
